### ISSUE TITLE
Roadmap to v4

### ISSUE THREAD

**Issue by retraigo** [retraigo/lala#11]
- [ ] Make story generator decent.
- [x] Add named exports for each file.
- [ ] Actually do something with `weebify`.
- [ ] Get rid of exports on utils (unless they seem necessary).
- [ ] Make it so that the code doesn't look like some sick animal's puke.
